version: '3'
services:
    db:
        image: postgres:13-alpine
        restart: always
        volumes:
            - ./conf/postgresql/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            TZ: "Asia/Shanghai"
            POSTGRES_PASSWORD: Fim741235896
        networks:
            - dev-network
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
        environment:
            TZ: "Asia/Shanghai"
        networks:
            - dev-network
    redis:
        image: 'redis:alpine3.11'
        restart: always
        hostname: redis
        container_name: redis-server
        ports:
         - 6379:6379
        environment:
            TZ: "Asia/Shanghai"
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./conf/redis/data:/data/
        networks:
            - dev-network
networks:
    dev-network: 
        driver: bridge
        # ipam:
        #     driver: default
        #     config:
        #     - subnet: 10.10.0.0/16