FROM alpine:latest

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
  echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && \
  apk --no-cache add ca-certificates && \
  apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
  echo "Asia/Shanghai" > /etc/timezone

WORKDIR /app

COPY ./bin/app /app/
COPY ./conf/config.local.json /app/conf/config.local.json
# Copy the Pre-built binary file from the previous stage

# Command to run the executable
ENTRYPOINT ["/app/app"]
CMD []