@host = http://localhost:9090
@remote = http://open.yunplus.io:19580

@appid = ceaa191a


### 注册一个新的mqtt用户
POST {{host}}/biz/mqttuser/create
Content-Type: application/json

{
    "isSuperuser": true,
    "username": "fpmuser3",
    "appid":"{{appid}}",
    "password":"fpmpassword4"
}