@host = http://localhost:9090
@remote = http://open.yunplus.io:19580

@appid = ceaa191a


### 注册一个新的mqtt用户
POST {{host}}/mqttuser/create
Content-Type: application/json

{
    "isSuperuser": true,
    "username": "fpmuser3",
    "appid":"{{appid}}",
    "password":"fpmpassword3"
}


### 注册一个新的生产mqtt用户
POST http://open.yunplus.io:19580/mqttuser/create
Content-Type: application/json

{
    "isSuperuser": true,
    "username": "fpmuser2",
    "appid":"{{appid}}",
    "password":"fpmpassword2"
}