@host = http://localhost:9000
@sn = ff123123
@device = light
@brand = lg01
@pid = 1
@appid = a0001

### 注册一个设备
POST {{host}}//device/{{device}}/{{brand}}/create
Content-Type: application/json

{
    "sn": "{{sn}}",
    "projectId": "{{pid}}",
    "appId": "{{appid}}",
 }